### ISSUE TITLE
waveSharp bug/error : Invalid floating point when switching between tabs 

### ISSUE THREAD

**Issue by grytom** [CorBer/waveSharp#1]
**Describe the bug**
"Invalid floating point operation" error message in Windows release, Linux is working fine.

**To Reproduce**
1.) Launch the application
2.) do NOT open any image file
3.) Click on any tab (PreProcess / Batch / Interface)
4.) Click back to Processing tab
5.) "Invalid floating point operation"

**Expected behavior**
Do not show error message

**Operating system and version**
 - GNU/Linux with Wine
 - Windows 7

**Comment by CorBer** [comment]
Hi Grytom,
Thanks for reporting, I will send you a link to test a possible solution.

cheers
Cor

**Comment by grytom** [comment]
Yep, now it works fine.

**Comment by CorBer** [comment]
Thanks for reporting, I will take this into the current code. If we have enough issues I will upload an upgrade of this. But in the mean time we are developing on. 

cheers
Cor
