### ISSUE TITLE
waveSharp bug/error : GTK2 warning

### ISSUE THREAD

**Issue by grytom** [CorBer/waveSharp#11]
**Describe the bug**
Switching to PreProcess tab raises warning

**To Reproduce**
1. start waveSharp
2. Open an image
3. Click into any field in Processing, Batch or Interface tab
4. Click PreProcess tab and warning is raised

**Expected behavior**
Do not show warning

**Screenshots**
![PreProcess](https://user-images.githubusercontent.com/86200535/212406361-0402c649-7efa-470d-b71f-d1b94a093117.jpg)

**Operating system and version**
 - GNU/Linux with GTK2 widgetset

**Comment by CorBer** [comment]
Please report the version no ...

**Comment by CorBer** [comment]
Unfortunately I cannot recreate this error.

**Comment by grytom** [comment]
V0.1.0.19
It is not doing every time.
I can look at this bug after you release the source code.

**Comment by CorBer** [comment]
Hi,

That will take some time, I will start releasing the code as soon as most of the features are in and after proper documentation. But I will PM you for this.

**Comment by grytom** [comment]
I have found which component is responsible for that warning message. I will try to find a solution for it and inform you about it.

**Comment by CorBer** [comment]
grytom reported a more detailed sequence needed to create the warning:
1.) Click PreProcess
2.) Click inside DirectoryEdit edit field to gain focus
3.) Click Batch
4.) Click PreProcess - editing field lost focus, but still work fine
5.) Click Batch
6.) Click PreProcess - button next to editing field is not drawn yet and GTK2 wants to give it a focus, because that component as whole is visible and enabled. Therefore showing warning message.

**Comment by CorBer** [comment]
The next version will have this updated.

**Comment by grytom** [comment]
Changing visibility works. Since GTK2 is the only widgetset affected, I suggest to aim the code for GTK2 only using {$ifdef LCLGTK2} {$endif}

Procedure TMainForm.ProcessOptionsChange(Sender: TObject);
Begin
   if image_loaded then
   If ProcessOptions.ActivePage = ProcessingTab Then
     Begin
      Convolve_and_show('ProcessingTab', True);
      batch_loaded := False;
     End;
   {$ifdef LCLGTK2}
   if ProcessOptions.ActivePage = OptionsTab then
     begin
        DirectoryEdit1.visible:=false;
        DirectoryEdit1.visible:=true;
     end;
   {$endif}
End;

______________________________________________________________
