### ISSUE TITLE
waveSharp bug/error : processing using Resize only works when saving as PNG

### ISSUE THREAD

**Issue by CorBer** [CorBer/waveSharp#15]
A user reported that Batch processing with resize active (other than 100%) does not work properly, the application does run but does not save the files. 
This seems to be the case for any file that you are saving using resize as a TIFF file. Saving as PNG is working as planned.

**Comment by WujoWojtas** [comment]
Hi, im c# developer with 10yrs of experience

I could help in development of wavesharp for Windows. Pascal is not a
problem ;)

If you think I could be usefull, plesase reply :)

Regards

czw., 2 lut 2023, 07:35 użytkownik CorBer ***@***.***>
napisał:

**Comment by CorBer** [comment]
Hi Wujo,

I have asked you before in a PM and you thusfar did not react. Please use a PM to discuss this as this is not part of the "issue".

cheers
Cor
