### ISSUE TITLE
waveSharp bug/error :  waveSharp will not open a tiff file generated by Registax 6.1.0.8

### ISSUE THREAD

**Issue by tonyjc001** [CorBer/waveSharp#22]
**Describe the bug**
A clear and concise description of what the bug/error is. waveSharp will not open a tiff file generated by Registrax 6.1.0.8. I get a message that says file cannot be opened but no further information. The tiff file can be opened by all the other software I have.

**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. start waveSharp
2. Open file
3. .Get popup box that says "Cannot open file"
4. See enclosed error

**Expected behavior**
I expect the file to open and be available for processing.

**Screenshots**
If applicable, add a screenshot to help explain your problem.

**Operating system and version**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 10 

**Additional context**

**Comment by tonyjc001** [comment]
If I take the same tiff file, run it through AffinityPhoto and then open it in waveSharp everything works fine. The tiff file is 33mb non zip tiff file.

**Comment by CorBer** [comment]
Hi,

That points towards an issue with the TIFF format, I havent heard this before. But most people also do not use TIFF generated by RegiStax for processing in waveSharp. Can you describe at what stage of RegiStax you saved the file ?

regards
Cor

**Comment by tonyjc001** [comment]
I will leave it with you. It is not a major problem for me as I was experimenting using different stacking software with various sharpening offerings. It would be good to get it fixed in a future build as I can see why newer users of Registax might want to use waveSharp as it is newer and offers different features.

**Comment by CorBer** [comment]
Thanks for reporting, the programming module I use inside the software to read/write TIFF is not something I can easily change myself. RegiStax was by most imagers seen as software to mainly sharpen the images. Stacking is mainly done in other software like astrostakkert. waveSharp replaces the sharpening stage of RegiStax.

**Comment by tonyjc001** [comment]
That is interesting. I find that stacking in Registax gives the most consistent results compared to the other options I tried. I have gone back to using Registax for stacking. Wavelets still give the best results for sharpening over Lucy-Richardson deconvolution.

**Comment by tonyjc001** [comment]
I have tried that and it is a very good solution. Thank you for the help and suggestions.
