### ISSUE TITLE
waveSharp v. 0.2 not starting on Mac Notebook Pro on Monterey

### ISSUE THREAD

**Issue by hrnts2000** [CorBer/waveSharp#23]
**Describe the bug**
A clear and concise description of what the bug/error is.

**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. attenpt to start waveSharp 
2. waveSharp not starting 
3. See enclosed error

**Operating system and version**
 - OS:  macOS Monterey 
 - Version 12.1

**Additional context**

[error log.txt](https://github.com/CorBer/waveSharp/files/12099768/error.log.txt)

**Comment by CorBer** [comment]
Hi,

As the documentation states we only got this running on ventura and later. Development on Mac was (I dont have a Mac myself) done by another member of our testteam and the Lazarus-pascal development system seemed not to be on par with the windows/linux development system. This is therefore not a bug but a clear limitation of the software. There is no easy solution for this as I cannot test/develop on a Mac myself.

cheers
Cor

**Comment by hrnts2000** [comment]
Good morning, 

thanks for the reply. I still use Monterey on my Mac, to prevent updates from possibly making it impossible to use VirtualBox and the virtual machines that I sometimes use for old software. I tried to use these virtual machines on my own to run software like DSS and Registax, but they still gave me problems. Actually (unfortunately...) the Mac, although very stable, is not as flexible as Windows machines.
Best regards

Renato
