### ISSUE TITLE
Source code archives do not contain source code / no licence published

### ISSUE THREAD

**Issue by ajeb78** [CorBer/waveSharp#28]
The zip and tar.gz source code archives do not contain any source code. Either they need updating to include the source code (plus a licence document) or removing. I'm not clear which as the repository is unclear as to whether this is open source or not, and if so what the licencing terms are.

**Comment by CorBer** [comment]
Hi,

This is open-source but currently mainly a prototype.  The software is created using the Lazarus Pascal environment and although the code is easy to share its not so easy to set things up. 

If you are interested in collaboration or want to use the code just send me a mail.

cheers
Cor

**Comment by CorBer** [comment]
https://github.com/CorBer/waveSharp/releases/download/v0_2/WaveSharpV_02_20R_sourcecode.zip

This is the sourcode that was used to produce the v0_2 prototype. Its mainly UNCOMMENTED and not 100% clean code. But as you were interested this is what I used to make the program.

cheers
Cor

**Comment by ajeb78** [comment]
Cheers. I'm no expert at writing pascal so I won't be much use in collaboration on this, but I was interested in having a look at some of the algorithms, particularly the convolution, to see whether it could give me ideas for improving the convolution code in Siril.
