### ISSUE TITLE
waveSharp 0_2 bug/error : Batch mode does NOT convolve with RGB method

### ISSUE THREAD

**Issue by RedLionNJ** [CorBer/waveSharp#29]
**Describe the bug**
When processing in batch mode, with Convolve set to RGB, the correct settings are not applied to any images

**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. start waveSharp
2. Click on 'Batch'
3. Load multiple images
4. Using the Processing tab, set Convolve to RGB and sharpen the current image
5. Return to the Batch tab and preview the batch
6. You will see the displayed image does not become as sharp as it was in step 4
7. Click on the Processing tab again - the image now appears sharpened once more
8. If you had done a 'Save Batch' from the batch tab, the saved images would not be as sharp, either

**Expected behavior**
I expected Batch mode to apply the sharpening as defined in the Processing tab

**Screenshots**
Not necessary.  But setting Convolve to RGB is key to replicating this bug.

**Operating system and version**
Windows 10 & Windows 7

**Additional context**
I tried this on three different laptops. Reproducible on all.

**Comment by CorBer** [comment]
Hi Grant,

When I start updating the software I will (try to) solve this. Wont be any time soon as this is the time of year when I do mainly woodworking/gardening. 

cheers
Cor

**Comment by CorBer** [comment]
Just checked and it is indeed isolated to the RGB processing during batch. Dont know why will check the source now

**Comment by CorBer** [comment]
Code shows no missing steps, will need to dive into that later this year.

**Comment by CorBer** [comment]
A change to the code has been tested and seems to work as planned. This will be repaired in the next update.
