### ISSUE TITLE
waveSharp bug/error : filename length

### ISSUE THREAD

**Issue by lmatias2** [CorBer/waveSharp#31]
**Describe the bug**
Dile name length limitation

**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. start waveSharp
2. Open an image file with long name (more than 20 for example. 
3. Process and attempt to save as
4. The program will display the same name with _WS at the end. Accept to save. 
5. The final filename is not the requested. 

**Expected behavior**
Correr name on file stored file.

**Screenshots**
If applicable, add a screenshot to help explain your problem.

**Operating system and version**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 11

**Additional context**
Also, big images do not ZOOM out as registax use to do

**Comment by CorBer** [comment]
Hi, 

Thanks for this report. I will look into this. 
The option to "overview" large images is simply not part of the current version. I am working on the next update that will (its getting tested currently) allow overviewing a larger image. 

cheers 
Cor

**Comment by CorBer** [comment]
Ive tested you report but cannot replicate the issue:
The file I loaded was called 
2022-08-21-0729_2-2022-08-21-0729_2-U-L-Jup_ZWO ASI224MC_pipp_lapl6_ap39_Drizzle15.PNG
and it got saved as
2022-08-21-0729_2-2022-08-21-0729_2-U-L-Jup_ZWO ASI224MC_pipp_lapl6_ap39_Drizzle15_WS.PNG

Please share in more detail and if possible with screenshots what goes wrong.

cheers
Cor

**Comment by CorBer** [comment]
Hi, 

Please respond on my request

**Comment by lmatias2** [comment]
Try tiff format, that’s the option I am using

Regards,

Luis A Matías
***@***.***

**Comment by CorBer** [comment]
Ive tried that also
2023-01-14-0001_9-U-L-Jup_AS_P35_lapl5_ap32.tif
and after saving
2022-07-23-0742_9-Saturn ASI224MC_AS3_TIF_WS.png
Please show exactly what you are doing and which filenames you are usign so I can see if it has to do with certain characters in the filename.  Without a clear documented example I am probably not able to find out what goes wrong.

**Comment by lmatias2** [comment]
Attached some screenshots

Regards,

Luis A Matías
***@***.***

**Comment by CorBer** [comment]
Hi,

Unfortunately  there are no screenshots visible ... 

cheers
Cor

**Comment by lmatias2** [comment]
Added the file to GitHub.

Regards,

Luis A Matías
***@***.***

**Comment by lmatias2** [comment]
Here are the pictures

![namecreated](https://github.com/CorBer/waveSharp/assets/146407235/fb5aeda4-1aa4-4e15-b6db-e23b3bb47d3a)
![proposedimagename](https://github.com/CorBer/waveSharp/assets/146407235/047658bc-4185-4b83-91e1-c4efcf7cd519)
![wholescreen](https://github.com/CorBer/waveSharp/assets/146407235/8a6eb7af-b5a5-4fb5-a43a-f9119a09850d)

**Comment by CorBer** [comment]
Is this an external drive (letter is I) ? I wonder if the file with the WS subscript has not been saved onto another location on your PC instead of on the Drive. Another thing to test, what happens if you change that " " in the filename after "bin1" into a "_". Still unclear what happens, its clear that its BTW not a filename of 20 characters but far more as the drive and the path are part of a filename. But we will find out what is going on !

**Comment by CorBer** [comment]
Hi,

Luckily one of my good helpers creating waveSharp (Grant) has pointed out that your filename contains a "." in the filename itself as it uses 91.1. You cannot/should not use "." in filenames as they are used to determine the change from filename to extension. So please change that and see if it now behaves as expected.

cheers
Cor

**Comment by lmatias2** [comment]
Hi Cor.

Replacing the period made a difference, nevertheless, all modern operating systems (iOS, Windows and LINUX) allow the use of spaces (multiple) and multiple periods (‘.’) in the file names. Single period is only a limitation of the ancient MSDOS operating system. The files are opened with no issues and the names displayed correctly, how can be so hard to place a period after the end of the “File name:” field and append to it the file extension corresponding to the save type?

When reading the file name (if it includes the extension in the string) you only have to search for the first period from the end of the string.

I guess, I do not understand from were the limitation comes. I sort of live with it with Registax because I never expected a fix for it, it was end of life. Maybe now is a good time to fix the bug.

BTW, I like your software very much.

Regards,

Luis A Matías
***@***.***

**Comment by CorBer** [comment]
Hi Luis,

I will look into this once more but it seems to be less trivial than one might think and although modern systems allow the usage of '.' and ' ' in filenames that does in my eyes not mean that it is good practice. In the programming language I am using (Pascal) the routines to extract filenames are clearly having issues with this. I could add separate routines to detect the usage of multiple '.' in a filename but thusfar you are the 1st (as far as I remember) person that has reported this also for RegiStax. So ... see it as a limitation :) Thanks for reporting  because as a programmer I can only know about issues when people take the time/effort to report them.

cheers
Cor

**Comment by lmatias2** [comment]
I do not program in Pascal since 1983, but with my limited time I can accept the challenge to help if you wish.

Regards,

Luis A Matías
***@***.***

**Comment by CorBer** [comment]
Hi Luis,

The code is allready available and you can have a look at:
https://github.com/CorBer/waveSharp/releases/download/v0_2/WaveSharpV_02_20R_sourcecode.zip

Be aware that this is programmed under Lazarus using a freepascal compiler, that way its real freeware. Just see if you can see/test a proper solution, if so its possible to see how we incorporate that in the next update.

cheers
Cor

**Comment by lmatias2** [comment]
Try this:

 

Procedure TMainForm.SaveFileDialogExecute(Sender: TObject);

Var

   saving_file: String;

 

   p: Integer;

   w,h:integer;

   fdir:string;

   // fext:string;

   fname:string;

Begin

   fdir := ExtractFileDir(current_filename);

   //fext:= ExtractFileext(current_filename);

   fname:=extractFilenameOnly(current_filename);

   w:=memory_image.width-1;

   h:=memory_image.height-1;

 

   //set filename for resized/cropped/trimmed image

   if savetrimfillcheckbox.checked then

   begin

      if (ImageTrimEdgeSpin.Value>0) and (EdgeOptions.itemindex=0) then   //trim the edge

        begin

          w:=Memory_Image.width-1-2*ImageTrimEdgeSpin.Value;

          h:=Memory_Image.height-1-2*ImageTrimEdgeSpin.Value;

        end;

      SavePictureDialog1.FileName:=fdir+directoryseparator+fname+'_w'+inttostr(w)+'_h'+inttostr(h); // +fext;

   end;

 

   //ROI overrules TRIM filename

   if SaveROIcheckbox.checked then

    begin

      w:=ROI_Rect.Width;

      h:=ROI_Rect.Height;

      if (ImageTrimEdgeSpin.Value>0) and (EdgeOptions.itemindex=0) then   //trim the edge

        begin

          w:=Memory_Image.width-1-2*ImageTrimEdgeSpin.Value;

          h:=Memory_Image.height-1-2*ImageTrimEdgeSpin.Value;

        end;

      SavePictureDialog1.FileName:=fdir+directoryseparator+fname+'_w'+inttostr(w)+'_h'+inttostr(h);  // +fext;

 

   end ;

 

   if (SaveResizedcheckbox.checked) then //resize

   begin

       w:=ScaleImageWidthspin.Value;

       h:=round(h*ScaleImageFloatspin.Value/100);

       SavePictureDialog1.FileName:=fdir+directoryseparator+fname+'_w'+inttostr(w)+'_h'+inttostr(h);  // +fext;

   end;

 

   If SavePictureDialog1.Execute Then

     Begin

      saving_file := SavePictureDialog1.FileName;

      //force a full processing run if limit is down to create a full image to save

      If limitprocessingbutton.Down Then

        Begin

         WaveletRect.Top := 0;

         WaveletRect.Left := 0;

         WaveletRect.Width := Memory_Image.Width - 1;

         WaveletRect.Height := Memory_Image.Height - 1;

         convolve_and_show('fullRect before saving');

        End;

 

      //do not allow . in the filename (to prevent double extensions)

      // p := pos('.', saving_file);

      // If p > 0 Then

      //    saving_file := copy(saving_file, 0, p - 1);

 

      saving_file := saving_file + '.' + SavePictureDialog1.GetFilterExt;

      savePictureDialog1.Title := saving_file;

 

      If fileExists(saving_file) Then

        Begin

         If MessageDlgPos('File exists, overwrite ?', mtWarning,

            mbyesno, 0, Mainform.Left + Mainform.Width div 2,

            Mainform.Top + Mainform.Height div 2) = mrYes Then

            SaveImageFromMemory(saving_file);

        End

      Else

         SaveImageFromMemory(saving_file);

 

     End;

 

End;

**Comment by CorBer** [comment]
Hi,

It is always handy to mark the section you have changed. In this case is this the only section ?
**//do not allow . in the filename (to prevent double extensions)
 // p := pos('.', saving_file);
 // If p > 0 Then
 //    saving_file := copy(saving_file, 0, p - 1);**

As that section (you suggest to comment out) is there not by chance but was added intentionally  I will first need to check back to see what lead me to add this. 

cheers
Cor

**Comment by CorBer** [comment]
I have had a good look at the code and this section "do not allow . in the filename" is there for a long time. I will see into this once more to see what I can do about it. Just removing it probably is going to give other issues that I rather resolve before changing the code.

cheers
Cor

**Comment by GreatAttractor** [comment]
Cor,
I suggest identifying the extension as the standard libraries of Rust ([std::path::Path::extension](https://doc.rust-lang.org/std/path/struct.Path.html#method.extension)) and C++ ([std::filesystem::path::extension](https://en.cppreference.com/w/cpp/filesystem/path/extension)) do:

- no extension, if there is no `.` in the file name
- no extension, if the file name begins with `.` and has no other `.` within
- otherwise, the portion of the file name after the final `.`

**Comment by CorBer** [comment]
Hi Philip,

I think creating separate routines for this purpose is not necessary. Freepascal has all the tools onboard to do this. The only issue was - as I see it now - that I used my code from RS6 as a base for several sections. RS6 was based on the windows version of 2011 and my version of Delphi (used at the time) could not deal with "." in the filename (at whatever location).  So I think the suggestion of luis is probably good enough to get this running as planned.

cheers
Cor

**Comment by lmatias2** [comment]
Saw you closed the issue? Did my fix work?

**Comment by CorBer** [comment]
Hi Luis,

If you read the messages above you will see that I have tested your proposed solution and had no issues. I have therefore added this to the current new code I am building for the next test-release (0_3).  

cheers
Cor

**Comment by CorBer** [comment]
Try testing this: 
https://github.com/CorBer/waveSharpDevelopment/releases/download/v0.3start/waveSharp_V03_06_WIN64.zip

**Comment by lmatias2** [comment]
Go this the first time, when I dragged the image into the application.

 



 

Filenames are now correct.

 

Thanks!

**Comment by lmatias2** [comment]
Also, a command window opened in the background. When you try to close it the whole application ends

 

 

 

From: ***@***.*** ***@***.***> 
Sent: Wednesday, October 11, 2023 9:07 AM
To: 'CorBer/waveSharp' ***@***.***>; 'CorBer/waveSharp' ***@***.***>
Cc: 'Author' ***@***.***>; ***@***.***
Subject: RE: [CorBer/waveSharp] waveSharp limitation : filenames with additional dots are not saved properly (Issue #31)

 

Go this the first time, when I dragged the image into the application.

 



 

Filenames are now correct.

 

Thanks!

**Comment by CorBer** [comment]
Hi,

All your screenshots (I guess you added those) are missing but the most important is that it is working. The command-window is a logscreen that I use during debugging, wont be there when I release the update.

**Comment by lmatias2** [comment]
![IMG_9978](https://github.com/CorBer/waveSharp/assets/146407235/8df5e3f3-f250-439f-8136-c6a10d39d319)

**Comment by CorBer** [comment]
Hi Luis,

That was after a drag and drop it seems. Please document more clearly what you are doing as this makes it a bit too much guesswork. What filetype did you drag & drop ? Share the file so I can test it and this is not part of this issue so pleaase open an new request. 

cheers
Cor

**Comment by CorBer** [comment]
Thanks
