### ISSUE TITLE
Saving and color

### ISSUE THREAD

**Issue by jmarkmanner** [CorBer/waveSharp#34]
Hi Cor, thanks for RS and WS! FWIW, when I use V0.2.0.20, I'm seeing two issues:
1. the Histogram AutoBalance results in a color balance that is different (and to me not correct), as compared to the same process in RG6.  I'll attach a screenshot of both.
2. When I use the "save" button, it won't save into the directory I'm in. To get an image saved I have to direct that it be saved to the desktop. Perhaps I've got a setting wrong.

Thanks! Mark Manner
![WS RS autobalance comp](https://github.com/CorBer/waveSharpDevelopment/assets/149181781/95b5d7b8-701c-4ae6-9523-0dc2f19ca599)

**Comment by CorBer** [comment]
Closing as the original poster has not added any further information within 3 weeks.
