### ISSUE TITLE
waveSharp 0_2 : loading a raw camera file does not work

### ISSUE THREAD

**Issue by craphead** [CorBer/waveSharp#36]
I open wavesharp (Win10, 64 bit, 16GB) and I open an Olympus raw- .orf file, and sliders in right panel have no effect on image.
So, I try to open the image as a .png file.  Still no joy.  Sliders have no effect. What am I missing?  I used registax and it always worked for me.  Why can't I get wavesharp to work?
**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. start waveSharp
3. ...
4. See enclosed error

**Expected behavior**

**Screenshots**
If applicable, add a screenshot to help explain your problem.

**Operating system and version**

**Additional context**

**Comment by CorBer** [comment]
Hi,

I dont see the screenshot with the error unfortunately. Next to that, this software is not ment to work with raw files. We are building it to work with 16bit PNG and TIFF files. With which software did you convert your raw file to PNG ?   cheers Cor

**Comment by craphead** [comment]
With Lightroom. But it converted to 8 bit pngs.
  
I will try a 16 bit. Thanks
  

  

  

  
  
  
  
  
>

**Comment by CorBer** [comment]
Moving this to the discussion section.
