### ISSUE TITLE
waveSharp 0_2 : loading a large file (45Mb PNG) does not work

### ISSUE THREAD

**Issue by drs1969** [CorBer/waveSharp#37]
Ok very 1st time using this software - so possible / probably I'm doing it wrong!
Windows 11 laptop running 22H2 - 4k laptop screen 

**Describe the bug**
Histogram doesn't update and respond as I would expect eg as Photoshop histogram does. 
SO in looking at the RGB histograms - I'd expect moving the slider to change the shape of the histogram. In either the weights and shifts tab or the RGB MidTones and Clip tab. And so far my 'move the sliders a lot and see what happens' technique isn't doing anything I can see.  If I click the refresh icon between the linear and the auto histo options - nothing happens. 
I tried this using a 45Mb stacked png image from Autostackert. 

Hope this is of some value. And if I'm doing it wrong then so be it. And thanks for writing this software. 

**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. start waveSharp
3. ...
4. See enclosed error

**Expected behavior**

**Screenshots**
If applicable, add a screenshot to help explain your problem.

**Operating system and version**

**Additional context**

**Comment by CorBer** [comment]
Hi,

A 45Mb PNG file sounds to me like something we have thusfar not even tested. I suggest starting your usage with a smaller file (1000x1000 pixels or so). How large is this PNG in terms of pixel-dimensions ?

cheers
Cor

**Comment by CorBer** [comment]
Closing the issue since the original poster has not supplied further details

**Comment by CorBer** [comment]
Wait until the next release is there. Probably less than a week to go for that.
