### ISSUE TITLE
No processing of out of view parts of images

### ISSUE THREAD

**Issue by Hubert-gtHub** [CorBer/waveSharp#39]
Hello!

I'm new to WaveSharp. I noticed the following and it looks like an anomaly.

**Bug description**

The hidden parts of images too large to fit on the screen are not processed when the region of interest encompasses the entire image (which is the default behavior after loading).

When the region of interest is reduced, it is no longer possible to deliberately hide part of it by using the scrollbars (the anomaly can no longer happen apparently).

If some parts of an image have been previously processed and then scrolled out of view, the saved image seems to be fully processed (I didn't check whether it was the result of the 1st or 2nd processing that was applied to the hidden area).

_Letter to Santa Claus :-) Maybe adding a zoom out functionality to the main window?_

**Steps to reproduce the behavior from the start of waveSharp.**

1. Start waveSharp
2. Click on 'load image'
3. Image is too large to fit on the screen
4. Apply a "strong" wavelett processing to differentiate the processed/unprocessed parts of the image
5. Click on 'Save' - png format (tiff not tested)
6. Out of view parts of the image are not processed - see screen capture and attached examples.

**Expected behavior** 

_Processing should apply to the full extent of the image._

**Screenshots** 

![01-screen-grab](https://github.com/CorBer/waveSharp/assets/151971181/0f1f49c7-bbed-452b-92aa-68b80fc480e6)

Left and right parts of the image are still blurry:

![02-partially_processed_img](https://github.com/CorBer/waveSharp/assets/151971181/f57be58b-0f9c-4415-bf56-0079ed26a26b)

Fully processed image:

![03-fully_processed_img](https://github.com/CorBer/waveSharp/assets/151971181/124aeb4d-8d93-49d8-aeff-07740e743cb1)

**Operating system and version**

- OS:     Ubuntu
- Version: 20.04 LTS x86_64 #99~20.04.1
- Kernel: 5.15.0-89-generic 

Many thanks for your amazing work, hope it helps!

**Comment by CorBer** [comment]
![Screenshot at 2023-11-25 07-11-24](https://github.com/CorBer/waveSharp/assets/1329760/9c51e38f-29b7-4533-9bcf-0dee75d34d8a)
Hi Hubert,

I hope that the next update we are working on will solve these issues. If not please share it once more. As you can see in the screenshot we now have a full -view option also visible. 

Thanks for reporting,

Cor
