### ISSUE TITLE
waveSharp bug/error : When using "Tab" key, the field sequnce is not sorted

### ISSUE THREAD

**Issue by Ruediger3** [CorBer/waveSharp#4]
Hi Cor,

when using TAB key to navigate between the input fields/sliders, the sequence is more or less random. Therefore e.g. it is not possible to quickly jump between the sliders back and forth using the TAB. 

Thank you!
Rüdiger

**Comment by CorBer** [comment]
Hi,
A proper Tabsequence is NOT a part of the current setup, if the application becomes more mature this can be adressed. Most people select controls by clicking on them.

cheers
Cor
