### ISSUE TITLE
waveSharp bug/error : Crashing after opening (macOS)

### ISSUE THREAD

**Issue by Domee66** [CorBer/waveSharp#45]
I tried to open the application, and I got the following error:
 .... 
**EDIT removed by maintainer.** A raw dump of errors on a Mac are not usefull to debug issues.

**Comment by CorBer** [comment]
Read the release notes please: waveSharp for MAC (released) RUNS ON MAC VENTURA !!

**Comment by Domee66** [comment]
Thanks for the reply. Yes, I have read it, but I thought it runs on macOS 12 as well, not only on Ventura.

**Comment by CorBer** [comment]
The message was not clear enough it seems, but you have at least shown that it does not. Development for MAC in the current programming-environment is not working as planned so to test the next update you will have to use Wine on a Mac to run the default windows version.
