### ISSUE TITLE
waveSharp bug/error : Tool does not know to distinguish between monochrome (single color) and displays black and white

### ISSUE THREAD

**Issue by lmatias2** [CorBer/waveSharp#46]
**Describe the bug**
Tool does not know to distinguish between monochrome (single color) and displays black and white.
I have a tiff picture of the Sun shot in H-Alpha (red), the tools displays with gray rendering

**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. start waveSharp
3. ...
4. See enclosed error

**Expected behavior**

**Screenshots**
If applicable, add a screenshot to help explain your problem.

**Operating system and version**

**Additional context**

**Comment by lmatias2** [comment]
I have the image, but it is from a SONY Camera, too big to upload. How can I upload or provide it to you?

**Comment by lmatias2** [comment]
Using version 0.3.0.8

**Comment by CorBer** [comment]
Hi

V03.08 is NOT a release... so upgrade to v1.0 beta first. The software checks if multiple colour channels are present or not. If only one colour is presented it switches to B/W but you can press the colour/bw button in the icon bar to switch to colour.

**Comment by CorBer** [comment]
In case you dont know the interface, on page #5 of the preliminary interface documentation this is shown.

**Comment by lmatias2** [comment]
That solved the problem. How can I move the ROI withing the image? The image is 7952 x 5304

**Comment by CorBer** [comment]
Read the interface documentation please.
