### ISSUE TITLE
Drag and drop waveSharp bug/error : 

### ISSUE THREAD

**Issue by Ke1thJ** [CorBer/waveSharp#48]
**Describe the bug**
Wavesharp will not allow the user to drag and drop images as shown in the Registax v6 screen. 

**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. start waveSharp
2. Click on image to be loaded into Wavesharp.
3.left click on the image and drag image into Wavesharp.

**Expected behavior :
Image to open in Wavesharp as it does in Registax v6
![Registax v 6 1](https://github.com/CorBer/waveSharp/assets/155236543/239d5629-4dc5-4e52-bc16-6c8fed7c53d6)
![Wavesharp1](https://github.com/CorBer/waveSharp/assets/155236543/8ddf9874-512a-4485-bdcb-1ed21fce8560)

**Screenshots**
If applicable, add a screenshot to help explain your problem.

*Windows 10 Pro. 64 bit.

**Comment by CorBer** [comment]
Have you tried using PNG/TIFF as those are the formats that I (when testing in Linux) can drag and drop without problems ?  JPEG is not a format I would recommend to use in waveSharp as its only 8bit and suffers from compression

**Comment by CorBer** [comment]
Closing this "issue" as the original poster has not replied for a week.
