### ISSUE TITLE
waveSharp bug/error : Histogram Window: Sliders cannot be moved via cursor keys

### ISSUE THREAD

**Issue by Ruediger3** [CorBer/waveSharp#5]
Hi Cor,

I could not move the sliders via cursor keys, which allows a very sensitive adjustment, though the slider was selected via mouse. 
If the value is adjusted in the text boxes via sliders, the curve is adjusting, but the slider does not move and shows wrong values.

Thank you!
Rüdiger

![2023-01-12_09h38_11](https://user-images.githubusercontent.com/65772654/212018595-80f64b52-0d5d-497e-9af1-a302297115c2.png)
![2023-01-12_09h39_15](https://user-images.githubusercontent.com/65772654/212018611-2b03a6cb-780d-432c-b966-11ad92ebaf6b.png)

**Comment by CorBer** [comment]
Hi,

You can adjust accurately with the scrollwheel of your mouse, manual editing the fields of the controls is not fully working it seems. 

cheers
Cor

**Comment by CorBer** [comment]
In the next update the scrollwheel will be active

**Comment by RedLionNJ** [comment]
Hi Cor,

This one is peculiar. Rudiger has a point, but the impression I got from his bug report was a slightly different point.

On the histogram form, the RGB sliders are disconnected from the spinners. The sliders cannot be “selected” via the mouse, but can be dragged using it. But when you raise the mouse button, the slider is not left in a selected mode. And that’s ok.  But when you drag the slider, it has an effect on the image but no effect on the number displayed in the spinner.  And when you change the number in the spinner, it has no effect on the position of the slider.

I have a nagging feeling we’ve been here sometime before.



Sent from Mail for Windows

From: Rüdiger
Sent: Thursday, January 12, 2023 3:40 AM
To: CorBer/waveSharp
Cc: Subscribed
Subject: [CorBer/waveSharp] waveSharp bug/error : Histogram Window: Sliderscannot be moved via cursor keys (Issue #5)

Hi Cor,
I could not move the sliders via cursor keys, which allows a very sensitive adjustment, though the slider was selected via mouse.
If the value is adjusted in the text boxes via sliders, the curve is adjusting, but the slider does not move and shows wrong values.
Thank you!
Rüdiger

**Comment by CorBer** [comment]
Hi Grant,

No, the spinners rudiger was referrening to are NOT connected to the sliders. The sliders on the tab of RGB weights/shifts are for the SHIFTS and the spinners are the WEIGHTS. These are therefore NOT connected ...

cheers
Cor
