### ISSUE TITLE
waveSharp bug/error :  ROI/Fullscreen checkbox resets to ROI even when Hold All Settings is enabled

### ISSUE THREAD

**Issue by AnthonyEWesley** [CorBer/waveSharp#51]
ROI/Fullscreen button does not honour the "Hold All Settings" checkbox, and always resets to ROI when an image is loaded.

The correct behavior is for the ROI/Fullscreen button to stay unchanged when "Hold All Settings" is enabled and the user loads a new image.

**Comment by AnthonyEWesley** [comment]
How about the case where a user loads a new image that is the same dimension as the old one, with "Hold All Settings" enabled the ROI/FI should not change.

Tested on Windows 11 x64

cheers,
Anthony

**Comment by CorBer** [comment]
That is not what the loading function looks at, it checks where the topic is and tries to place a box around it for processing. That is what it does by default, if you load two jupiter images in a sequence with the same dimensions but with jupiter shifted to a different location the ROI will follow. 

Which "problem" does this cause ? If I can understand the issue that this creates I might think of a way to prevent that issue. Be aware that currently I am not in a development-stretch as I first want to get the beta tested properly. There is - under development - all kind of stuff that can still be added. But I rather have a proper v1.0 beta first.


Cor

**Comment by AnthonyEWesley** [comment]
The issue is that I have to always reset the ROI/FI button to "Full Image" every time I load an image. I do not want to use ROI at all, but WS keeps defaulting back to that when I load a new image. How about an option to let the user choose the behavior that they want - ie either the current behavior or keep the ROI/FI unchanged when loading a new image.

cheers,
Anthony

**Comment by AnthonyEWesley** [comment]
accidentally closed by me, re-opened.

**Comment by CorBer** [comment]
I will add that option as an enhancement for the next update. The main motivation to set the user in the 1:1 (ROI) mode is to work on the image as it was recorded. When using full screen you dont see exactly how the image will look like after wavelets etc as you get a compressed view on your screen. 
Cor

**Comment by CorBer** [comment]
Ive changed the way this works. When hold all (selected in the PRE tab) is ON the status of the FULL/ROI processing button will not be altered during the load of a new image.
