### ISSUE TITLE
Wavelet processing is incorrect when a new image is loaded

### ISSUE THREAD

**Issue by AnthonyEWesley** [CorBer/waveSharp#52]
When a new image is loaded to replace an existing image, either using File->Open or drag-n-drop, the processed image as shown is incorrect. The image is too dark and overprocessed. If the user then takes any action that causes the image to refresh then the correctly processed image will be displayed.

Tested using a TIFF format image generated by Autostakkert (both versions 3 and 4).

**Comment by CorBer** [comment]
Hi Anthony,

Is this in Linux or Windows ?

Cor

**Comment by AnthonyEWesley** [comment]
Hi Cor, thanks for looking into this.

I am using 1.0beta on Windows 11 x64. I don't know what other image formats this might apply to, I only generate TIFF images from Autostakkert. I will test PNG later today.

cheers, Anthony
cheers, Anthony

**Comment by AnthonyEWesley** [comment]
oops, somehow I accidentally marked this as closed. My apologies

**Comment by CorBer** [comment]
Hi Anthony,

This "effect" is probably related to processing using LUM and HSV ? Please share a screenshot after opening the file that will at least show me which settings are active. 

cheers
Cor

**Comment by AnthonyEWesley** [comment]
Here are a set of screenshots for you, and the images, and the wavesharp settings in use. let me know if you have trouble reproducing this error.

1. WS opened with no action taken. The file to be loaded is highlighted in the file browser
2. The image file loaded via drag-n-drop. No sharpening applied
3. WS preset j20240120-ir750 loaded. Note only part of Jupiter is processed as the ROI is too small.
4. The ROI/FI button is pressed to switch to fullscreen so I can see all of Jupiter. The processing is correct in this view
5. The next image is loaded via drag-n-drop over the first. Note WS has reverted to ROI and also shows an incorrectly processed image (it's very over-processed).
6. The view after I press the ROI/FI button to again switch to full image. Now the processing is correct and I can see all of Jupiter.

Windows 11 x64
WS 1.,0beta

I hope this helps.

cheers, Anthony
![WS-3](https://github.com/CorBer/waveSharp/assets/157260837/e8b1c517-5109-45c6-ace1-fe2a2b3d9a8f)
![WS-4](https://github.com/CorBer/waveSharp/assets/157260837/3e9fddef-24d3-4a0f-a1be-734e8b27ec70)
![WS-5](https://github.com/CorBer/waveSharp/assets/157260837/16bc44b8-57de-473a-95fe-62b7dab489c0)
![WS-6](https://github.com/CorBer/waveSharp/assets/157260837/c16716e5-43b2-4c9c-9fe5-0c44de13c69b)
![WS-1](https://github.com/CorBer/waveSharp/assets/157260837/0e08da0e-f7c5-46e2-8639-ce5d9d8f0889)
![WS-2](https://github.com/CorBer/wav
[2024-01-20-0914_1-AW-IR750.zip](https://github.com/CorBer/waveSharp/files/14014727/2024-01-20-0914_1-AW-IR750.zip)
eSharp/assets/157260837/bfc383cf-877f-4147-a9cd-92a4a92853ff)
[waveSharp-settings.zip](https://github.com/CorBer/waveSharp/files/14014741/waveSharp-settings.zip)

ps my only options below for posting this entry on github are 'Close as Completed" or "Close as Not Planned". There seems no way for me to post this entry and leave this issue open ?? Neither of these is correct but I guess I have to pick one...

**Comment by AnthonyEWesley** [comment]
Here are a set of screenshots for you, and the images, and the wavesharp settings in use. let me know if you have trouble reproducing this error.

1. WS opened with no action taken. The file to be loaded is highlighted in the file browser
2. The image file loaded via drag-n-drop. No sharpening applied
3. WS preset j20240120-ir750 loaded. Note only part of Jupiter is processed as the ROI is too small.
4. The ROI/FI button is pressed to switch to fullscreen so I can see all of Jupiter. The processing is correct in this view
5. The next image is loaded via drag-n-drop over the first. Note WS has reverted to ROI and also shows an incorrectly processed image (it's very over-processed).
6. The view after I press the ROI/FI button to again switch to full image. Now the processing is correct and I can see all of Jupiter.
Windows 11 x64
WS 1.,0beta

I hope this helps.

cheers, Anthony

WS-1
![WS-1](https://github.com/CorBer/waveSharp/assets/157260837/05e9c905-253c-4fd7-8d57-5d8429d157a2)

WS-2
![WS-2](https://github.com/CorBer/waveSharp/assets/157260837/303ba99

WS-3
![WS-3](https://github.com/CorBer/waveSharp/assets/157260837/4b934ac6-5e4a-42fc-8d33-2c412082b883)
9-a893-4ba7-8b17-c004b88fea0e)

WS-4
![WS-4](https://github.com/CorBer/waveSharp/assets/157260837/f021c857-c3b6-49ab-a993-9c1eae1ca56b)

WS-5
![WS-5](https://github.com/CorBer/waveSharp/assets/157260837/ef9283b0-9e72-4d68-8c7d-fe76ad13e4ba)

WS-6
![WS-6](https://github.com/CorBer/waveSharp/assets/157260837/a1b1ef83-0899-45f2-a4ea-24684e7b47e9)

Settings 
[waveSharp-settings.zip](https://github.com/CorBer/waveSharp/files/14014814/waveSharp-settings.zip)

Raw Images
[2024-01-20-0914_1-AW-IR750.zip](https://github.com/CorBer/waveSharp/files/14014815/2024-01-20-0914_1-AW-IR750.zip)

**Comment by CorBer** [comment]
Also, in the case of this image I would not go to full view but stay in the 1:1 view and enlarge the ROI (the topleft/bottomright corners allow this). That isnt part of the bug as the "main" reported bug is the darkening/overprocessing.

**Comment by AnthonyEWesley** [comment]
Hi Cor, yes I have "Hold All Settings" enabled.

I have tried resizing the ROI , but it reverts to 512x512 when I load a new image or save and restart so that's even slower than pressing the ROI/FI button every time I load a new image.

cheers

**Comment by CorBer** [comment]
The limit to resize the ROI to 512x512 only is clearly a bug and unexpected. Up for repair in the next update.

**Comment by CorBer** [comment]
In the next update the ROI will not be limited to 512x512
