### ISSUE TITLE
waveSharp bug/error :  Save preset field pre-filled with "." on startup

### ISSUE THREAD

**Issue by AnthonyEWesley** [CorBer/waveSharp#53]
**Describe the bug**
A clear and concise description of what the bug/error is.

The Save Preset field is pre-filled with a period (".") on startup. Anything the user types in there is appended to this, so wavelet save names end up with an unwanted leading period. The user has to notice this and manually delete the period before they type in a name for their settings.

**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. start waveSharp
2.  Look at the "Save Preset" field. It contains a period (".") that should not be there.

**Expected behavior**
The Save Preset field should be empty on startup

**Screenshots**

**Operating system and version**
Windows 11
1.0Beta

**Comment by CorBer** [comment]
Hi Anthony,

This "." was explicitly added  so its part of the design. This is NOT a bug.

cheers
Cor
