### ISSUE TITLE
waveSharp bug/error :  Error message "Cannot focus a disabled or invisible window"

### ISSUE THREAD

**Issue by AnthonyEWesley** [CorBer/waveSharp#54]
**Describe the bug**

This error message appears when applying the wavelet settings here to the attached image

**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. start waveSharp
2. load the attached image
3. load the given wavelet settings
4. The error message will appear

**Expected behavior**

The error message should not appear

**Screenshots**
The following files are attached:

- application error screenshot
- source image (tif)
- wavelet settings

**Operating system and version**
 - Windows 11 x64
 - 1.0beta

**Additional context**
![Screenshot (19)](https://github.com/CorBer/waveSharp/assets/157260837/5e399065-9f2f-4a52-9f62-1b64d1927c4a)
[j20240121-xxx.txt](https://github.com/CorBer/waveSharp/files/14004679/j20240121-xxx.txt)
[2024-01-21-0931_3-AW-CH4.zip](https://github.com/CorBer/waveSharp/files/14004683/2024-01-21-0931_3-AW-CH4.zip)

**Comment by CorBer** [comment]
Thanks for sharing this, I will repair that in the next update as this is unwanted behaviour.

cheers
Cor

**Comment by CorBer** [comment]
Ive just solved this error, so its definitely part of the next update.
