### ISSUE TITLE
waveSharp bug/error :  Inconsistent user interface behavior

### ISSUE THREAD

**Issue by AnthonyEWesley** [CorBer/waveSharp#57]
**Describe the bug**
A clear and concise description of what the bug/error is.

Inconsistent behavior in the user interface. Typing into most fields and pressing ENTER triggers actions but typing a value into the Presets->Save field and pressing ENTER does nothing.

**To Reproduce**
Steps to reproduce the behavior from the start of waveSharp.
1. start waveSharp
2. Load an image and set the wavelet values as appropriate using the sliders (the values do not matter for this bug).
3. type a name into the Preset->Save field and press ENTER
4. The preset is not saved. If you quit and restart WS the preset was not saved.

**Expected behavior**

Typing a value into the Preset->Save field and pressing ENTER should save the values under the given name.

**Screenshots**
If applicable, add a screenshot to help explain your problem.

**Operating system and version**
 - OS: Windows 11 x64
 - Version 0.1beta

**Additional context**

**Comment by CorBer** [comment]
You need to use the SAVE button ... that is for the presets necessary as I cannot detect the user pressing "ENTER" in a field. This behaviour is consistent in the software for all locations where you can enter texts. SO this is NOT a bug but it works like this by design. 

cheers
Cor
