### ISSUE TITLE
waveSharp bug/error : Installer doesn't succeed when using local admin account on domain computer

### ISSUE THREAD

**Issue by skybadger** [CorBer/waveSharp#67]
**Describe the bug**
A clear and concise description of what the bug/error is.
Installer doesn't succeed when using local admin account on domain computer
Fails with error that "python.dll is not found" using windows v2 installer

**To Reproduce**
Steps to reproduce the behaviour from the start of waveSharp.
1. start waveSharp
3. ...
4. See enclosed error

Install wavesharp as user account with local admin to install python for everyone under windows
specify custom install if not using local admin 
specify standard install if using local admin  

**Expected behavior**
Python variables attached to environment path  - they are pre-pended. 
Pythonpath.ini setup correctly  - not 
Wavesharp_v2.exe to execute without error - fails to find the Python dll . 

Pythonpath.ini has only stub entries for the Python and PythonDll lines What should they be ? 
cmd line - "Python --version" returns python312
Python 312 is installed in c:\program files\python312

**Screenshots**
If applicable, add a screenshot to help explain your problem.
![image](https://github.com/user-attachments/assets/f2107907-a5da-4b36-858d-b6e7b9f3ad71)

**Operating system and version**
 Win 10 Ver22H2 19045.5247

**Additional context**
Manually pip installed numpy and open cv and updated PIp to latest version.

**Comment by CorBer** [comment]
Hi,

The only thing you need to do is to change the file pythonpath.ini to have two correct lines that point waveSharp to the location of the dll.

The pythonpath.ini is inside the directory you installed waveSharp.
1st line of pythonpath.ini should be the directory where the dll can be found
2nd line is the filename of the DLL

I cannot comment on the details of your "problem" as I am not a windows user. The installer is ment to deal with pre-installed python also if that has a proper link in the registry of windows. So you can :
a) try to install once more and see if waveSharp can find python in the registry
b) modify the pythonpath.ini as described above.

cheers
Cir

**Comment by CorBer** [comment]
As an example, this is pythonpath.ini on a test-computer with windows I have standing around.

C:\users\corbee\AppData\Local\Programs\Python\Python310\
python310.dll

**Comment by skybadger** [comment]
Thanks Cor

I have 

"c:\program files\Python312"

"c:\program files\Python312\python312.dll"

As the paths indicated on the pythonpath.ini now but still have same problem.  

I have python installed for all users under “c:\program files\Python312 “ and did a manual install of numpy and opencv-python using into that location. 

Currently re-installing for all users using a domain admin. 

Did you mean “registry” ? I canlt see any need for the windows registry to be involved unless there is something inside the .exe file that does this ? 

 

Regards

Mike

**Comment by skybadger** [comment]
I have amended python path to have just the name of Python312.dll as the entry 

While re-installing as Domain admin I have come across the issue which may shed more light  : 



 

Followed by 



 

I don’t think anyone expects a file called python3.12.dll so not sure what its looking for here. Any tests I can do to meet your installer code demands ? 

 

Clicking OK a few times eventually leads to the splash screen for Wavesharp as if its finished installing OK. 

Regards

Mike

**Comment by CorBer** [comment]
Hi,

You cannot use this as a mail-service, your images do NOT show up and the original -texts of my reply DO show up. 

cor

**Comment by CorBer** [comment]
As stated before, the pythonpath.ini needs to have one line with the directory 
and one line with the name of the DLL. Why yours is called python3.12.dll is beyond my knowledge, its not default for sure.

**Comment by skybadger** [comment]
Hi Cor 

In spite of the installer issues described in the last email , the program has started and is now running for a normal domain user. 

The only additional change I made was to add a python312.exe copy of Python.exe in the c:\program files \Python312 directory. 

Regards

Mike

**Comment by CorBer** [comment]
I have not seen this before and I also cannot test this, but as it works. Its not an issue for you anymore. Maybe others experience the same and will find this helpfull. Closing this now.

Cor
